[platformio]
default_envs = ideaspark_esp32
test_dir = test

[env:ideaspark_esp32]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
board_build.flash_size = 16MB
board_build.partitions = app3M_spiffs9M_fact512k_16MB.csv
board_upload.flash_size = 16MB
monitor_speed = 921600
upload_speed = 921600
lib_deps =
  https://github.com/lovyan03/LovyanGFX.git#fb7cec222726b92676e26126246d59f70f04ced2
  https://github.com/bitbank2/JPEGDEC.git#86282979224c8a32fd51e091ed5a35b0c699a52b
  ESP32Async/ESPAsyncWebServer
  ESP32Async/AsyncTCP
  ricmoo/QRCode

[env:native]
platform = native
test_framework = unity
